name: cfhkip

# on:
#   schedule:
#     - cron: '00 2 * * *'

on: [push]

env:
  BASE_API: ${{ secrets.BASE_API }}
  EMAIL: ${{ secrets.EMAIL }}
  KEY: ${{ secrets.KEY }}
  QUERY: ${{ secrets.QUERY }}
  TESTURL: ${{ secrets.TESTURL }}

permissions:
  contents: write
      
jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Start getting IPs"
        
    - name: Check my code
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r ./requirements.txt

    - name: Set execute permissions
      run: chmod +x ./CloudflareST
      
    - name: Run script
      run: python main.py --baseapi "$BASE_API" --query "$QUERY" --testurl "$TESTURL"
    
    - name: remove old data
      run: rm -rf ./ips.txt
      
    - name: Commit and push changes
      run: |
        git config --local user.name 'Garfyyy'
        git config --local user.email 'garfy@stu.gxnu.edu.cn'
        git add .
        git diff --quiet || git commit -m "Update results"
        git push origin main
